# Generated by Django 3.0.3 on 2020-02-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=3000)),
                ('create', models.DateField()),
            ],
            options={
                'ordering': ['-create'],
            },
        ),
    ]
